package main

import "fmt"

func main() {
	game := newGame()
	setDebug(game)
	game.cards.randomShuffle()
	// game.cards.displayAll()
	game.cards, game.board = game.dealBoard()
	game.board.display()
	game.currentCard().display()
	fmt.Println()
	game.cards.display()
	fmt.Println()
	game = game.getNextCard()
	game.currentCard().display()
	fmt.Println()
	game.cards.display()
	fmt.Println()
	game = game.getNextCard()
	game.currentCard().display()
	fmt.Println()
	game.cards.display()
	fmt.Println()
	game = game.getNextCard()
	game.currentCard().display()
	fmt.Println()
	game.cards.display()
	fmt.Println()
	game = game.getNextCard()
	game.currentCard().display()
	fmt.Println()
	game.cards.display()
	fmt.Println()
	game = game.getNextCard()
	game.currentCard().display()
	fmt.Println()
	game.cards.display()
	fmt.Println()
	game = game.getNextCard()
	game.currentCard().display()
	fmt.Println()
	game.cards.display()
	fmt.Println()
	game = game.getNextCard()
	game.currentCard().display()
	fmt.Println()
	game.cards.display()
	fmt.Println()
	game = game.getNextCard()
	game.currentCard().display()
	fmt.Println()
	game.cards.display()
	fmt.Println()
	game = game.getNextCard()
	game.currentCard().display()
	fmt.Println()
	game.cards.display()
	fmt.Println()
}
